### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by jhonatanoliveira** [gluon-api/gluon-api#1]
Hello.
Just letting you know about a little typo in the "Getting Started with the Gluon Interface" example.
The following line of code `for i, batch in enumerate(train_data):` from the _README.md_ file example should be `for i, (data, label) in enumerate(train_data):` as shown in the [Jupyter notebook](https://github.com/gluon-api/gluon-api/blob/master/tutorials/mnist-gluon-example.ipynb).

**Comment by srochel** [comment]
thanks, fixed.
