### ISSUE TITLE
Can't find gluon.image.color_normalize() or gluon.nd.array()

### ISSUE THREAD

**Issue by mawah** [gluon-api/gluon-api#11]
Hi folks,

I'm using MXNet version 0.12.0 on Ubuntu and trying to follow the advice in [docs/model_zoo.rst](https://github.com/gluon-api/gluon-api/blob/master/docs/model_zoo.rst) on image normalization:

>  You can use gluon.image.color_normalize for such transformation:
> ```
> image = image/255
> normalized = gluon.image.color_normalize(image,
>                                          mean=gluon.nd.array([0.485, 0.456, 0.406]),
>                                          std=gluon.nd.array([0.229, 0.224, 0.225]))
> ```
Unfortunately, I get errors such as the following:
```
>>> from mxnet import gluon
>>> test = gluon.nd.array([0.485, 0.456, 0.406])
AttributeError: module 'mxnet.gluon' has no attribute 'nd'
```
 What am I doing wrong here? Thanks in advance!

**Comment by edmBernard** [comment]
I think it's a error `gluon.nd.array` might be `mx.nd.array`

**Comment by mawah** [comment]
Aha yes, thanks @edmBernard! That works, as does `mx.image.color_normalize()`. Does anyone know whether model_zoo.rst should be fixed? (I suppose there might be a planned update to gluon that would make the current code in model_zoo.rst run as-is?)

**Comment by lupesko** [comment]
@mawah note that the gluon-api repository defined the gluon-api spec, not a concrete implementation.
If you want to dive into using Gluon, you will need to use a concrete implementation of the spec, which currently is MXNet's. So gluon.nd.array in MXNet is mxnet.nd.array, etc.

Check out https://mxnet.incubator.apache.org/versions/master/api/python/gluon/model_zoo.html which is the MXNet/Gluon version of the Model Zoo tutorial you were looking into.

HTH.
