### ISSUE TITLE
proposal: enable gitter community for gluon-api repo?

### ISSUE THREAD

**Issue by ezeeetm** [gluon-api/gluon-api#13]
It would be great to enable the 'gitter' feature for the gluon-api repo, similar to how mxnet has done [here](https://gitter.im/dmlc/mxnet).

To do this, you can:

- sign into [gitter.im](https://gitter.im) with you github creds.
- depending on what screen you are presented with, choose either the '+' icon in the bottom left, or the green 'create your own community' button
- choose the green text link in 'do you want to start a community for one of your github projects?'
- choose 'my repo' (or org if you want to do it for the whole gluon-api org account)
- choose `gluon-api repo`
- click through the rest of the process

**Comment by lupesko** [comment]
Interesting idea. Let's keep this issue open to see if other community members want to chime in.

**Comment by lupesko** [comment]
No feedback from community - closing.
Feel free to re-open if you think this was closed in error.
